# fly.toml app configuration file generated for fintrackv1 on 2025-03-12T15:03:20-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'fintrackv1'
primary_region = 'lax'

[build]
  dockerfile = 'Dockerfile'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
